install.packages("tidyverse")
install.packages("janitor")
install.packages("cowplot")
install.packages("flextable")
install.packages("dlookr")
install.packages("caret")
install.packages("leaps")
install.packages("cowplot")
install.packages("glmnet")
install.packages("randomForest")
install.packages("gbm")
install.packages("plsr")


#install.packages("")
#install.packages("")
