---
title: 'EDA students performance in Mathematics'
author: "Erick Calderon-Morales"
date: ' Fall 2021'
due_date: ""
output:
  prettydoc::html_pretty:
    highlight: pygments
    theme: cayman
    toc: yes
    number_sections: no
    toc_depth: 1

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,comment = "", fig.align = 'center',
					  fig.width = 20, fig.height = 15)
```



```{r knitr, include = FALSE}

# Save figures in specific place

knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.comments = TRUE,
                      
                      # Include code?
                      echo           = TRUE,
                      
                      error          = FALSE,
                      fig.align      = "center",
                      
                      # Path to where to store pdf single figures
                      fig.path       = paste0("../1_eda/eda_figures_tables/", "/"),
                      fig.width      = 20,
                      fig.height     = 15,
                      message        = FALSE,
                      warning        = FALSE)
```


```{r cleanup-docs, cache = FALSE,echo = FALSE}

# save a html copy file in a specific place
#doc.files <- c(list.files(pattern = "pdf"),
#               list.files(pattern = "html"),
#               list.files(pattern = "docx"))

#for (file in doc.files) {
#  cambiar nombre
#    file.rename(file, file.path("../../hw1/", file))
#}
```


```{r libaries, message=FALSE, warning=FALSE, cache=FALSE}
library(tidyverse)
library(janitor)
library(tidyr)
library(cowplot)
library(DT)
library(webshot)
library(flextable)
library(dlookr)
library(caret)
```

```{r}
# Load data
raw_data  <- read.table("../../data/raw_student-mat.csv", sep= ";", header=TRUE) 
```


# Data set for eda
```{r}
eda_data  <-  
    raw_data  %>% 
        clean_names() %>% 
  
        # Transform variables to numeric
        mutate(g3 = as.numeric(g3),
               g2 = as.numeric(g2),
               g1 = as.numeric(g1)) %>%
        
        # Transform chr type to factor
        mutate(across(where(is.character), as.factor)) %>% 
        
        # Transform intergers to factor except absences and age  
        mutate(across(where(is.integer), as.factor)) %>%
  
        # Add g3 as binary for part A2 of the project         
        mutate(g3_binary = factor(if_else(g3 >= 10,"pass","fail" )))   
      
```


```{r}
str(eda_data)
dim(eda_data)
```


```{r}
# Set names, exclude response variables (g3 and g3_binary)
predictors_names <- set_names(names(eda_data)[-c(33:34)])
```

# Figure 1
```{r message=FALSE, warning=FALSE, fig.width = 20, fig.height = 25}

histogram_plot <-  function(x) {
     ggplot(eda_data, aes(x = .data[[x]])) +
          geom_bar()  +
          geom_text(aes(label = scales::percent(..prop..), group = 1), 
                    stat= "count", position = position_dodge(width = 0.9), 
                    size = 7) +
          theme_bw() +
          #scale_y_continuous(labels = scales::percent) +
          theme(axis.text=element_text(size = 21),
                axis.title=element_text(size = 21,face = "bold"),
                axis.text.x = element_text(angle = 25, hjust = 1)) 
}

plots_predictors <- map(predictors_names[-c(30,31,32)], ~ histogram_plot(.x) ) 

cowplot::plot_grid(plotlist = plots_predictors, ncol = 4)
```





```{r}
# ft <- flextable( head( mtcars ) )
# ft <- autofit(ft)
# tf <- tempfile(fileext = ".png")
# if (FALSE) {
# if( require("webshot") ){
#   save_as_image(x = ft, path = "myimage.png")
# }
# }
```





# Table 1


```{r}
(table_1 <-   
  eda_data %>% 
    select(g1, g2, g3) %>% 
    describe() %>%
    flextable())

table_1 <- autofit(table_1)
#tf <- tempfile(fileext = ".png")
save_as_image(x = table_1, path = "../1_eda/eda_figures_tables/table_1.png")
```
# Table 2
```{r}
(table_2 <- 
    eda_data %>% 
      select(g3,g2,g1) %>% 
      cor() %>%
      as.data.frame() %>% 
      flextable())

table_2 <- autofit(table_2)
#tf <- tempfile(fileext = ".png")
save_as_image(x = table_2, path = "../1_eda/eda_figures_tables/table_2.png")
```


# Figure 2

```{r fig.height = 12, fig.width = 8}

g1_plot_outliers <- 
eda_data %>%  
  plot_outlier(g1) 

g2_plot_outliers <- 
eda_data %>%  
  plot_outlier(g2) 

g3_plot_outliers <- 
eda_data %>%  
  plot_outlier(g3) 



plot_grid(plotlist = c(g1_plot_outliers,
                       g2_plot_outliers,
                       g3_plot_outliers), ncol = 1)
```


# Figure 3

```{r width = 10, height = 20}
g3_boxplot <-  function(x) {
    ggplot(eda_data, aes(y = g3, x = .data[[x]])) +
     #geom_col(position = "fill") +
    geom_boxplot(outlier.shape = 14, outlier.size=2) +
    theme_light() +
    theme(axis.text=element_text(size = 15),
          axis.title=element_text(size = 15,face = "bold"),
          legend.position = "top",
          legend.key.size = unit(0.5, 'cm'),
          legend.title = element_text(size = 15)) 
          #legend.text = element_text(size = 12)) 

}


boxplots_g3 <- map(predictors_names[-c(3,30,31,32)], ~ g3_boxplot(.x) ) 

cowplot::plot_grid(plotlist = boxplots_g3 , ncol = 4)
```




#  Table 3

```{r}
(table_3 <- 
  eda_data %>% 
  select(-c(g1,g2,g3,g3_binary)) %>% 
  nearZeroVar(., saveMetrics= TRUE) %>% 
  flextable())

table_3 <- autofit(table_3)
#tf <- tempfile(fileext = ".png")
save_as_image(x = table_3, path = "../1_eda/eda_figures_tables/table_3.png")
```







# Save clean dataset

```{r}
clean_data  <-  
    raw_data  %>% 
        clean_names() %>% 
  
        # Transform variables to numeric
        mutate(g3 = as.numeric(g3),
               g2 = as.numeric(g2),
               g1 = as.numeric(g1),
               age = as.integer(age),
               absences = as.integer(absences)) %>%
        
        # Transform chr type to factor
        mutate(across(where(is.character), as.factor)) %>%
  
        # Add g3 as binary for part A2 of the project         
        mutate(g3_binary = factor(if_else(g3 >= 10,"pass","fail" )))   
```



```{r echo = FALSE}
if(!"clean_data_student_math_performance.csv" %in% dir("../../data/")) {
  
  write.csv(clean_data, file = "../../data/clean_data_student_math_performance.csv")
  print("Clean dataset saved")
  
  } else{

  print("Clean dataset saved")
  }
```









